func_pyt=('''abs() all() 	any() 	ascii()
bin() 	bool() 	bytearray() 	bytes()
callable() 	chr() 	classmethod() 	compile()
complex() 	delattr() 	dir() 	dict()
divmod() 	enumerate() 	eval() 	exec()
filter() 	float() 	format() 	frozenset()
getattr() 	globals() 	hasattr() 	hash()
hex() 	id() 	input() 	int()
__import__() 	iter() 	isinstance() 	issubclass()
len() 	list() 	locals() 	map()
max() 	memoryview() 	min() 	next()
oct() 	object() 	open() 	ord()
pow() 	property() 	print() 	range()
repr() 	reversed() 	round() 	set()
setattr() 	slice() 	sorted() 	str()
staticmethod() 	sum() 	super() 	tuple()
type() 	vars() 	zip()''')
fp=func_pyt.split()
#print(func_pyt)
print(fp)
n=input()
if n in fp:
    print('y')
else:
    print('N')